# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0614de23aab146a63e8d984f26fddb3fe7f0a87b68a9ab25d4d90fe81b75b02df88d32f67976cc22a57e52d0a19f6b642c15f60b51031118b0883246905bd54e

test:
  secret_key_base: 4bcd0c1786fedf5049ad7522cfa5e8c7d6550137229bc93fc09770baa359b30260243c3fed786500b2de159942d8ea4baca05a3b3fc76903558145fd3267a672

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
